// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4GkQ8ULMwYiWR4wl_iur7vyDdWtxhbng',
    appId: '1:419855959896:android:a6dd3d0aff403e826b072d',
    messagingSenderId: '419855959896',
    projectId: 'shoesly-e685d',
    storageBucket: 'shoesly-e685d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfqmBICvoqBeXv4JFPqIfQq548Q0UzMGg',
    appId: '1:419855959896:ios:95214531ff1c76f86b072d',
    messagingSenderId: '419855959896',
    projectId: 'shoesly-e685d',
    storageBucket: 'shoesly-e685d.appspot.com',
    androidClientId: '419855959896-6dndssgua5im025iebjs6lj5497rpi9c.apps.googleusercontent.com',
    iosClientId: '419855959896-9nfj6u64cc9c2g81gcobetnk4h6o4e3q.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoesly',
  );
}
